mode: commit
min_length: 3
allowed:
  - backend
  - backends
  - betteralign
  - config
  - crd
  - env
  - entrypoint
  - envtest
  - failsafe
  - frontend
  - frontends
  - gatewayclass
  - github
  - gitlab
  - golang
  - golangci
  - init
  - kubebuilder
  - kubeconfig
  - leaderelection
  - lifecycle
  - linter
  - linters
  - maxconn
  - mkdir
  - modfile
  - mutex
  - namespace
  - namespaces
  - parallelize
  - passthrough
  - reconciler
  - releaser
  - repo
  - runtime
  - slogger
  - ssl
  - sudo
  - taskfile
  - testenv
  - tcp
  - tls
  - ubuntu
  - unix
  - workdir
  - yaml
