enableAllRules = true

[rule.line-length-limit]
  arguments = [120]

[rule.import-alias-naming]
  arguments = ["^[a-z][a-z0-9_]*(V[0-9]+)?$"]

[rule.cyclomatic]
  arguments = [42]
[rule.cognitive-complexity]
  arguments = [42]

[rule.unhandled-error]
  arguments = ["fmt.Print", "fmt.Println", "strings.Builder.WriteString", "bytes.Buffer.WriteString"]

[rule.unexported-return]
  Disabled = true

[rule.exported]
  Disabled = true

[rule.package-comments]
  Disabled = true

[rule.max-public-structs]
  Disabled = true

[rule.add-constant]
  Disabled = true

[rule.redundant-import-alias]
  disabled = true

[rule.struct-tag] # tag inline unrecognized
  disabled = true

[rule.function-length]
  arguments = [30, 100]
