#https://taskfile.dev/
version: '3'

includes:
  ci:
    taskfile: taskfile-ci.yml
    flatten: true
  go:
    taskfile: taskfile-go.yml
    flatten: true
  kind:
    taskfile: tools/kind.yml
    flatten: true
  kubectl:
    taskfile: tools/kubectl.yml
    flatten: true
  git:
    taskfile: tools/git.yml
    flatten: true
  lint:
    taskfile: tools/golang-ci-lint.yml
    flatten: true
  generate:
    taskfile: tools/generate.yml
    flatten: true

tasks:

  ci:
    desc: 'do all the checks'
    cmds:
      - task: check-commit
      - task: tidy
      - task: format
      - task: licenses
      - task: generate
      - task: lint
      - task: test
      - task: govulncheck
