#https://taskfile.dev/
version: '3'

env:
  TASK_INTERNAL: true

includes:
  kind:
    taskfile: tools/kind.yml
    flatten: true
  kubectl:
    taskfile: tools/kubectl.yml
    flatten: true
  git:
    taskfile: tools/git.yml
    flatten: true
  lint:
    taskfile: tools/golang-ci-lint.yml
    flatten: true
  generate:
    taskfile: tools/generate.yml
    flatten: true
  haproxy:
    taskfile: tools/haproxy.yml
    flatten: true

tasks:

  ci:
    desc: 'do all the checks'
    cmds:
      - task: check-commit
      - task: tidy
      - task: format
      - task: licenses
      - task: generate
      - task: lint
      - task: test
      - task: govulncheck

  test:
    desc: 'run Go tests'
    cmds:
      - go test -v ./...

  tidy:
    internal: true
    desc: 'run Go mod tidy'
    cmds:
      - go mod tidy

  lint:
    desc: 'run Go linters'
    deps: [lint-version]
    cmds:
      - "{{.TMP_DIR}}/golangci-lint/{{.GOLANGCI_LINT_VERSION}}/golangci-lint run --timeout 15m --color always --max-issues-per-linter 0 --max-same-issues 0"

  format:
    internal: true
    desc: 'formats the code'
    cmds:
      - go tool gofumpt -l -w .

  licenses:
    internal: true
    dir: cmd/controller
    desc: 'check licenses'
    cmds:
      - |
          PROJECT="$(go list -m)"
          ALLOWED_LICENSES="$(<../../.allowed_license_types)"
          go tool go-licenses report --ignore "$PROJECT" --ignore "github.com/golang/freetype/raster" --ignore "github.com/golang/freetype/truetype" --ignore "oss.terrastruct.com/d2" .
          go tool go-licenses check --allowed_licenses="$ALLOWED_LICENSES" --ignore "$PROJECT"  --ignore "github.com/oktalz/present" --ignore "github.com/golang/freetype/raster" --ignore "github.com/golang/freetype/truetype" --ignore "oss.terrastruct.com/d2" .

  check-commit:
    internal: true
    cmds:
      - go tool check-commit

  govulncheck:
    internal: true
    cmds:
      - go tool govulncheck -show verbose ./...
