#!/command/with-contenv sh

if [ ! -e /etc/unified-controller/aux/haproxy-aux.cfg ]; then
	touch /etc/unified-controller/aux/haproxy-aux.cfg
	chgrp haproxy /etc/unified-controller/aux/haproxy-aux.cfg
	chmod g+w /etc/unified-controller/aux/haproxy-aux.cfg
fi
