apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: dual
  apiServerAddress: "127.0.0.1"
  apiServerPort: 7443
kind: Cluster
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      controllerManager:
          extraArgs:
            max-endpoints-per-slice: "5"
            node-cidr-mask-size-ipv4: "21"
    - |
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration
      metadata:
              name: config
      maxPods: 2048
  ## This is the same as kind-create-cluster but it is useful in dev purposes for debugging purpose and running HUG locally
  ## It uses kind-config-dev.yaml which does not map the ports to host machine
  ## Thus it is useful for local development where you can use 'as is' the examples in the example directory
  ## and run a local haproxy that can start and binds on the same ports as the ones used in the examples
