#https://taskfile.dev/
version: '3'

env:
  KUBECTL_VERSION: v1.32.2
  CONTROLLER_GEN_VERSION: v0.18.0
  K8S_VERSION: 1.32.2
  CLUSTER_NAME: "{{ default \"dev-controller\" .CLUSTER_NAME}}"
  DOCKER_FILE: "{{ default \"-build/Dockerfile\" .DOCKER_FILE}}"
  TMP: tmp

vars:
  CONFIG_DIR: "ci/kind/manifests"
  KIND_VERSION:
    sh: yq eval '.kind.version' taskfile-tools.yml
