#https://taskfile.dev/
version: '3'

env:
  KUBECTL_VERSION: v1.33.0
  K8S_VERSION: 1.33.1
  ENVTEST_VERSION: v1.33.0
  CLUSTER_NAME: "{{ default \"dev-controller\" .CLUSTER_NAME}}"
  DOCKER_FILE: "{{ default \"-build/Dockerfile\" .DOCKER_FILE}}"
  TMP: tmp
  GATEWAYAPI_CRDS_DOWNLOAD_URL: https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml

vars:
  CONFIG_DIR: "ci/kind/manifests"
  KIND_VERSION:
    sh: yq eval '.kind.version' taskfile-tools.yml
  API_DEFINITION_DIR: "api/definition"
