license:
  stage: security
  needs: ["diff", "tidy"]
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: "$CI_PROJECT_NAMESPACE != 'haproxy-controller/community' && $CI_PIPELINE_SOURCE == 'push'"
  image:
    name: $CI_REGISTRY_GO/golang:$GO_VERSION
    entrypoint: [ "" ]
  tags:
    - go
  before_script:
    - "sed -i 's/internal: true/internal: false/g' taskfile.yml"
  script:
    - task licenses
  after_script:
    - |
      if [ "$CI_JOB_STATUS" == "success" ]; then
        junit-report add --status=ok --message="license check passed successfully"
      else
        junit-report add --status=failed --message="licenses errors" --description="$(task licenses 2>&1)"
      fi
  artifacts:
    when: always
    paths:
      - junit-report.xml
    reports:
      junit: junit-report.xml
govulncheck:
  stage: security
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: "$CI_PROJECT_NAMESPACE != 'haproxy-controller/community' && $CI_PIPELINE_SOURCE == 'push'"
  image:
    name: $CI_REGISTRY_GO/golang:$GO_VERSION
    entrypoint: [ "" ]
  tags:
    - go
  before_script:
    - "sed -i 's/internal: true/internal: false/g' taskfile.yml"
  script:
    - task govulncheck
  after_script:
    - |
      if [ "$CI_JOB_STATUS" == "success" ]; then
        junit-report add --status=ok --message="vulnerability check passed successfully"
      else
        junit-report add --status=failed --message="vulnerabilities detected" --description="$(task govulncheck 2>&1)"
      fi
  artifacts:
    when: always
    paths:
      - junit-report.xml
    reports:
      junit: junit-report.xml
