apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: haproxy-controller
  name: haproxy-controller
  namespace: haproxy-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      run: haproxy-controller
  template:
    metadata:
      labels:
        run: haproxy-controller
    spec:
      serviceAccountName: haproxy-kubernetes-controller
      containers:
        - name: haproxy-controller
          image: haproxytech/kubernetes-controller:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: 2560Mi
            requests:
              memory: 2048Mi
          args:
            - --haproxyctrlconf-crd=haproxy-controller/haproxyctrlconf
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: stat
              containerPort: 31024
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-kubernetes-controller
  namespace: haproxy-controller
spec:
  selector:
    run: haproxy-controller
  type: NodePort
  ports:
    - name: stat
      port: 1024
      targetPort: 1024
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8443
      nodePort: 31443
      protocol: TCP
