// Copyright 2026 HAProxy Technologies LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cmd/generate-gwapi; DO NOT EDIT.

package gwapi

import (
	"bytes"
	"compress/gzip"
	_ "embed"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/Masterminds/semver/v3"
)

//go:embed v1.3.0-experimental.yaml.gz
var v130 []byte

//go:embed v1.4.0-experimental.yaml.gz
var v140 []byte

//go:embed v1.5.0-experimental.yaml.gz
var v150 []byte

// SupportedVersions lists all embedded Gateway API versions.
var SupportedVersions = []string{"v1.3.0", "v1.4.0", "v1.5.0"}

// versions maps semver version strings to their embedded gzipped CRD YAML.
var versions = map[string][]byte{
	"v1.3.0": v130,
	"v1.4.0": v140,
	"v1.5.0": v150,
}

// BundleVersionAnnotation is the annotation key used by Gateway API CRDs
// to indicate the bundle version.
const BundleVersionAnnotation = "gateway.networking.k8s.io/bundle-version"

// Get returns the embedded experimental Gateway API CRD YAML for the given version.
// The version can be specified with or without the "v" prefix (e.g., "1.3.0" or "v1.3.0").
// The embedded data is gzip-compressed and decompressed on the fly.
func Get(version string) ([]byte, error) {
	v, err := semver.NewVersion(version)
	if err != nil {
		return nil, fmt.Errorf("invalid version %q: %w", version, err)
	}
	key := "v" + v.String()
	compressed, ok := versions[key]
	if !ok {
		return nil, fmt.Errorf("unsupported Gateway API version %q, supported: %v", key, SupportedVersions)
	}
	return decompress(compressed)
}

// WriteCRDsToDir decompresses the embedded GWAPI CRDs for the given version
// and writes each YAML document as a separate file in dir.
// This is useful for envtest which needs a directory of individual CRD files.
func WriteCRDsToDir(version, dir string) error {
	data, err := Get(version)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}
	for i, part := range bytes.Split(data, []byte("\n---")) {
		trimmed := bytes.TrimSpace(part)
		if len(trimmed) == 0 {
			continue
		}
		name := filepath.Join(dir, fmt.Sprintf("gwapi-%02d.yaml", i))
		if err := os.WriteFile(name, trimmed, 0o644); err != nil {
			return fmt.Errorf("failed to write %s: %w", name, err)
		}
	}
	return nil
}

func decompress(data []byte) ([]byte, error) {
	r, err := gzip.NewReader(bytes.NewReader(data))
	if err != nil {
		return nil, fmt.Errorf("failed to create gzip reader: %w", err)
	}
	defer r.Close()
	return io.ReadAll(r)
}
