#https://taskfile.dev/
version: '3'

tasks:
  check-latest-version-tool:
    desc: 'check-latest-version'
    internal: true
    silent: true
    vars:
      LATEST_VERSION:
        sh: go list -u -m -json {{.PACKAGE}} | yq '.Update.Version // .Version'
      CURRENT_VERSION:
        sh: go list -u -m -json {{.PACKAGE}} | yq '.Version'
    cmds:
      - |
        if [ "{{.LATEST_VERSION}}" != "{{.CURRENT_VERSION}}" ]; then
          echo "{{.PACKAGE}} can be updated from {{.CURRENT_VERSION}} to {{.LATEST_VERSION}}"
        fi

  check-latest-versions:
    desc: 'tools-check-latest-versions'
    silent: true
    vars:
      PACKAGES:
        sh: go tool | grep "/" | sed 's/\/cmd.*//g' | tr '\n' ',' | sed 's/,$//'
    cmds:
      - for: { var: PACKAGES, split: ',' }
        task: check-latest-version-tool
        vars:
          PACKAGE: '{{.ITEM}}'

  default:
    cmds:
      - task: check-latest-versions
